parameters:
#    angelescuangelescu.example.class: Angelescu\angelescuBundle\Example

services:
#    angelescuangelescu.example:
#        class: %angelescuangelescu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
