parameters:
#    tudor_pag_pers.example.class: Tudor\PagPersBundle\Example

services:
#    tudor_pag_pers.example:
#        class: %tudor_pag_pers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
